/* Excel files stay in this browser. Preview and explicit confirmation precede writes. */
window.ExcelImport = (() => {
  const specs = {
    clients: {label:'Clients',fields:{name:'Client name *',site:'Site / address',contact:'Contact'}},
    invoices: {label:'Invoices',fields:{no:'Invoice number *',client:'Client name *',date:'Invoice date *',taxable:'Amount before GST',gst:'GST amount',total:'Total including GST'}},
    payments: {label:'Collections / receipts',fields:{receipt:'Receipt number *',invoice:'Invoice number *',date:'Payment date *',amount:'Amount received *',mode:'Account: Cash / Bank / UPI / Petty Cash *'}},
    expenses: {label:'Expenses',fields:{client:'Client name (blank = company)',receipt:'Reference / voucher number *',date:'Expense date *',category:'Category *',vendor:'Vendor / payee',description:'Description *',amount:'Total paid including GST *',gst:'GST included',account:'Payment account *'}}
  };
  const aliases={name:['clientname','customername','name','siteclientname'],site:['site','address','siteaddress','billingaddress'],contact:['contact','phone','mobile'],no:['invoiceno','invoicenumber','billno'],client:['client','clientname','customer','customername','site'],invoice:['invoice','invoiceno','invoicenumber'],date:['date','invoicedate','paymentdate','expensedate','invoicegenerationdate','paymnetdate'],taxable:['taxable','taxableamount','taxablevalue','amountbeforegst','grossamount'],gst:['gst','gstamount','taxamount'],total:['total','totalamount','invoicetotal','totalpayment'],receipt:['receipt','receiptno','receiptnumber','reference','voucherno'],amount:['amount','paidamount','paymentamount','totalpaid'],mode:['mode','account','paymentmode'],account:['account','paymentaccount','paidfrom'],category:['category','expensecategory'],vendor:['vendor','payee','supplier'],description:['description','particulars','details']};
  let sheets=[],selected=0,preview=null,fileName='',headerIndex=0;
  const norm=value=>String(value??'').trim().toLowerCase();
  const label=value=>norm(value).replace(/[^a-z0-9]/g,'');
  const byId=id=>document.getElementById(id);
  const error=message=>{byId('importError').textContent=message};
  function data(kind){return {clients,invoices,payments,expenses}[kind]}
  function validDate(value){
    if(value instanceof Date){if(Number.isNaN(value.getTime()))throw Error('Invalid date');return value.toISOString().slice(0,10)}
    if(typeof value==='number'){if(value<1||value>100000)throw Error('Invalid Excel date');return new Date(Date.UTC(1899,11,30)+Math.floor(value)*86400000).toISOString().slice(0,10)}
    const text=String(value??'').trim();let match=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);let year,month,day;
    if(match){[,year,month,day]=match}else{match=text.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(!match)throw Error('Use YYYY-MM-DD or DD/MM/YYYY dates');[,day,month,year]=match}
    const date=new Date(Date.UTC(Number(year),Number(month)-1,Number(day)));
    if(date.getUTCFullYear()!==Number(year)||date.getUTCMonth()+1!==Number(month)||date.getUTCDate()!==Number(day))throw Error('Invalid calendar date');
    return date.toISOString().slice(0,10);
  }
  function amount(value,optional=false){if(value===''||value==null){if(optional)return 0;throw Error('Amount is required')}const number=Number(String(value).replace(/[₹,\s]/g,''));if(!Number.isFinite(number)||number<0||number>1000000000)throw Error('Invalid amount');return roundMoney(number)}
  function required(value,name){const result=String(value??'').trim();if(!result)throw Error(name+' is required');return result}
  function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else if(!cell||quoted)quoted=!quoted;else throw Error('Invalid CSV quoting')}else if(char===','&&!quoted){row.push(cell);cell=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=char}if(quoted)throw Error('Unclosed CSV quotation');if(cell||row.length){row.push(cell);rows.push(row)}return rows}
  async function loadExcel(){if(window.ExcelJS)return;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';script.integrity='sha384-Pqp51FUN2/qzfxZxBCtF0stpc9ONI6MYZpVqmo8m20SoaQCzf+arZvACkLkirlPz';script.crossOrigin='anonymous';script.onload=resolve;script.onerror=()=>{script.remove();reject(Error('Excel reader could not load. Retry or save the sheet as CSV.'))};document.head.appendChild(script)})}
  function cellValue(cell){const value=cell.value;if(value&&typeof value==='object'&&!(value instanceof Date)){if('formula'in value||'sharedFormula'in value){if(value.result===undefined)return {importError:'Recalculate mapped formulas in Excel and save the file first'};return value.result}if(value.richText)return value.richText.map(p=>p.text).join('');if(value.text!==undefined)return value.text;if(value.error)return {importError:'Mapped cell contains a formula error'}}return value??''}
  function resetPreview(){preview=null;byId('importPreview').innerHTML='';byId('importApply').disabled=true;error('')}
  async function readRows(file){
    if(!file||file.size>10*1024*1024)throw Error('Use a file smaller than 10 MB.');
    let result;
    if(/\.csv$/i.test(file.name))result=[{name:file.name,rows:parseCSV((await file.text()).replace(/^\uFEFF/,''))}];
    else if(/\.xls[xm]$/i.test(file.name)){await loadExcel();const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(await file.arrayBuffer());result=workbook.worksheets.map(sheet=>{if(sheet.rowCount>10001||sheet.columnCount>100)throw Error('Use sheets with at most 10,000 rows and 100 columns.');const rows=[];for(let n=1;n<=sheet.rowCount;n++){const row=[];for(let c=1;c<=sheet.columnCount;c++)row.push(cellValue(sheet.getRow(n).getCell(c)));rows.push(row)}return {name:sheet.name,rows}})}
    else throw Error('Use .xlsx, .xlsm or .csv. Save older .xls files as .xlsx first.');
    if(!result.length||result.some(s=>s.rows.length>10001))throw Error('No usable sheets or too many rows.');return result;
  }
  async function read(file){resetPreview();sheets=[];if(!file)return;fileName=file.name;try{sheets=await readRows(file);byId('importSheet').innerHTML=sheets.map((sheet,i)=>`<option value="${i}">${escapeHTML(sheet.name)}</option>`).join('');selected=0;headerIndex=0;byId('importHeader').value=1;mapping()}catch(e){error(e.message)}}
  function mapping(){resetPreview();if(!sheets.length)return;selected=Number(byId('importSheet').value);headerIndex=Number(byId('importHeader').value)-1;const headers=sheets[selected]?.rows[headerIndex];if(!headers||headerIndex<0){error('Choose a valid header row.');return}const spec=specs[byId('importKind').value];byId('importMapping').innerHTML=Object.entries(spec.fields).map(([field,title])=>`<div class="field"><label for="map-${field}">${title}</label><select id="map-${field}" onchange="ExcelImport.resetPreview()"><option value="">Not mapped</option>${headers.map((header,i)=>`<option value="${i}" ${aliases[field]?.includes(label(header))?'selected':''}>${escapeHTML(header||'Column '+(i+1))}</option>`).join('')}</select></div>`).join('')}
  function convert(kind,row){
    if(kind==='clients')return {name:required(row.name,'Client name'),site:String(row.site??'').trim(),contact:String(row.contact??'').trim(),plan:'',rule:'Custom',visits:0,status:'Active'};
    if(kind==='invoices'){
      const matches=clients.filter(c=>norm(c.name)===norm(required(row.client,'Client name')));if(matches.length!==1)throw Error('Client not found or ambiguous; import clients first');
      const gst=amount(row.gst,true);const taxable=row.taxable!==''&&row.taxable!=null?amount(row.taxable):roundMoney(amount(row.total)-gst);const total=roundMoney(taxable+gst);
      if(taxable<=0||total<=0)throw Error('Invoice amount must be positive');if(row.total!==''&&row.total!=null&&Math.abs(amount(row.total)-total)>0.009)throw Error('Total must equal taxable amount plus GST');
      return {no:required(row.no,'Invoice number'),client:matches[0].id,date:validDate(row.date),taxable,gst,total,paid:0};
    }
    if(kind==='payments'){
      const invoice=invoices.find(i=>norm(i.no)===norm(required(row.invoice,'Invoice number')));if(!invoice)throw Error('Invoice not found; import invoices first');const id=accountIdByName(required(row.mode,'Account')),account=accounts.find(a=>a.id===id);if(!account)throw Error('Account not found');const paid=amount(row.amount);if(paid<=0)throw Error('Payment amount must be positive');return {receipt:required(row.receipt,'Receipt number'),invoice:invoice.id,date:validDate(row.date),amount:paid,mode:account.name};
    }
    const id=accountIdByName(required(row.account,'Account')),account=accounts.find(a=>a.id===id);if(!account)throw Error('Account not found');const paid=amount(row.amount),gst=amount(row.gst,true);if(paid<=0||gst>paid)throw Error('Expense/GST amount is invalid');let client=null;if(String(row.client??'').trim()){const matches=clients.filter(c=>norm(c.name)===norm(row.client));if(matches.length!==1)throw Error('Expense client not found or ambiguous');client=matches[0].id}return {client,allocations:[],receipt:required(row.receipt,'Reference'),date:validDate(row.date),category:required(row.category,'Category'),description:required(row.description,'Description'),vendor:String(row.vendor??'').trim(),account:account.name,amount:paid,gst};
  }
  function identity(kind,row){if(kind==='clients')return norm(row.name)+'|'+norm(row.site);return norm(kind==='invoices'?row.no:row.receipt)}
  function buildPreview(){resetPreview();if(!sheets.length)return error('Choose an Excel or CSV file first.');const kind=byId('importKind').value,mode=byId('importMode').value,fields=Object.keys(specs[kind].fields),map=Object.fromEntries(fields.map(field=>[field,byId('map-'+field)?.value??'']));const rows=sheets[selected].rows.slice(headerIndex+1),changes=[],errors=[],seen=new Set();let skipped=0;
    for(let index=0;index<rows.length;index++){const cells=rows[index];if(cells.every(value=>String(value??'').trim()===''))continue;try{const mapped=Object.fromEntries(fields.map(field=>[field,map[field]===''?'':cells[Number(map[field])]??'']));if(Object.values(mapped).every(value=>value===''||value==null))continue;for(const value of Object.values(mapped)){if(value?.importError)throw Error(value.importError)}const record=convert(kind,mapped),key=identity(kind,record);if(seen.has(key))throw Error('Duplicate reference in this sheet');seen.add(key);const existing=data(kind).find(item=>identity(kind,item)===key);if(kind==='expenses'&&existing&&map.client===''){record.client=existing.client??null;record.allocations=existing.allocations||[]}if(existing&&mode==='add'){skipped++;continue}if(kind==='invoices'&&existing&&record.total<invoicePaid(existing.id))throw Error('Invoice total is below recorded collections');if(kind==='payments'&&existing&&record.invoice!==existing.invoice)throw Error('An existing receipt cannot move to another invoice');changes.push({row:index+headerIndex+2,record,existingId:existing?.id,action:existing?'Update':'Add'});}catch(e){errors.push('Row '+(index+headerIndex+2)+': '+e.message)}}
    if(kind==='payments'){const projected=payments.map(p=>({...p}));for(const change of changes){const index=change.existingId===undefined?-1:projected.findIndex(p=>p.id===change.existingId);if(index>=0)projected[index]={...projected[index],...change.record};else projected.push(change.record)}for(const invoice of invoices){const paid=roundMoney(projected.filter(p=>p.invoice===invoice.id).reduce((sum,p)=>sum+p.amount,0));if(paid>roundMoney(invoice.total))errors.push('Collections exceed invoice '+invoice.no+' by '+money(paid-invoice.total))}}
    preview={kind,changes,errors,fingerprint:JSON.stringify(localSnapshot()),mode};byId('importPreview').innerHTML=`<p><b>${changes.filter(c=>c.action==='Add').length} new · ${changes.filter(c=>c.action==='Update').length} updates · ${skipped} skipped · ${errors.length} errors</b></p><p>Dates are preserved. Existing records change only in update mode. Invoice paid amounts must be imported as separate receipts.</p>`+(errors.length?`<ul style="color:var(--danger)">${errors.slice(0,30).map(e=>'<li>'+escapeHTML(e)+'</li>').join('')}</ul>`:'')+`<div class="table-wrap"><table class="table"><thead><tr><th>Row</th><th>Action</th><th>Reference</th><th>Date</th><th>Amount</th></tr></thead><tbody>${changes.slice(0,50).map(c=>`<tr><td>${c.row}</td><td>${c.action}</td><td>${escapeHTML(c.record.no||c.record.receipt||c.record.name)}</td><td>${escapeHTML(c.record.date||'')}</td><td>${c.record.total!==undefined?money(c.record.total):c.record.amount!==undefined?money(c.record.amount):'—'}</td></tr>`).join('')}</tbody></table></div>`;byId('importApply').disabled=errors.length>0||changes.length===0;
  }
  function apply(){if(!preview||preview.errors.length||!preview.changes.length)return;if(!cloudReady)return error('Sign in and load the workspace before importing.');if(JSON.stringify(localSnapshot())!==preview.fingerprint)return error('Records changed after preview. Preview again before importing.');if(!confirm(`Apply ${preview.changes.length} ${preview.kind} records? ${preview.mode==='update'?'Matching records will be updated.':'Existing records will be skipped.'}`))return;const list=data(preview.kind);let next=Math.max(0,...list.map(row=>row.id))+1;for(const change of preview.changes){const existing=list.find(row=>row.id===change.existingId);if(existing){const record={...change.record};if(preview.kind==='clients'){delete record.plan;delete record.rule;delete record.visits;delete record.status}Object.assign(existing,record)}else list.push({...change.record,id:next++})}saveData();render();renderFinance();renderReports();renderExpenseRegister();renderAccountRegister();resetPreview();error('Import applied locally. Check the cloud save status before closing.');}
  function open(){let dialog=byId('excelImport');if(!dialog){dialog=document.createElement('dialog');dialog.id='excelImport';dialog.style.cssText='width:min(900px,95vw);max-height:90vh;border:1px solid var(--border);border-radius:12px;background:var(--surface);color:var(--text);padding:20px';dialog.innerHTML=`<div style="display:flex;justify-content:space-between"><h2>Import / update Excel</h2><button class="btn" onclick="document.getElementById('excelImport').close()">Close</button></div><p>Import clients first, then invoices, then receipts. Import expenses separately. Use .xlsx, .xlsm or .csv; dates may be YYYY-MM-DD or DD/MM/YYYY. Files are read in your browser. VBA macros are never executed.</p><input type="file" id="importFile" accept=".xlsx,.xlsm,.csv" onchange="ExcelImport.read(this.files[0])"><div class="filters" style="margin:16px 0;flex-wrap:wrap"><label>Records <select id="importKind" onchange="ExcelImport.mapping()">${Object.entries(specs).map(([key,spec])=>`<option value="${key}">${spec.label}</option>`).join('')}</select></label><label>Sheet <select id="importSheet" onchange="ExcelImport.mapping()"></select></label><label>Header row <input id="importHeader" type="number" min="1" value="1" style="width:70px" onchange="ExcelImport.mapping()"></label><label>Duplicates <select id="importMode" onchange="ExcelImport.resetPreview()"><option value="add">Add new; skip existing</option><option value="update">Update matching references</option></select></label></div><div id="importMapping" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px"></div><p id="importError" role="alert" style="color:var(--danger)"></p><button class="btn" onclick="ExcelImport.buildPreview()">Preview import</button> <button id="importApply" class="btn primary" disabled onclick="ExcelImport.apply()">Confirm import</button><div id="importPreview"></div>`;document.body.appendChild(dialog)}dialog.showModal()}
  return {open,read,mapping,buildPreview,apply,resetPreview,readRows,validDate};
})();
