window.FinanceUI=(()=>{
 const el=id=>document.getElementById(id),text=(id,value)=>{if(el(id))el(id).textContent=value};
 let bankSheets=[],bankPreview=null,reviewing=null;
 function render(){
  if(!el('financeAnalysis')){const panel=document.createElement('div');panel.id='financeAnalysis';panel.className='card';panel.style.margin='16px 0';panel.innerHTML='<div class="card-head"><h3>Company P&L and cash flow</h3><div><input id="financeMonth" type="month" onchange="FinanceUI.render()"><button class="mini" onclick="document.getElementById(\'financeMonth\').value=\'\';FinanceUI.render()">All dates</button> <button class="btn" onclick="FinanceUI.openBank()">Upload bank statement</button></div></div><div style="padding:16px"><p id="financeTotals"></p><p id="financeCash"></p><p>Client contribution excludes unallocated supplier costs and company overheads. Shared costs use your percentages.</p><div class="table-wrap"><table class="table"><thead><tr><th>Client</th><th>Revenue, ex GST</th><th>Allocated costs, ex GST</th><th>Contribution</th></tr></thead><tbody id="financeClients"></tbody></table></div><h3>Expense list</h3><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Purpose</th><th>Category</th><th>Allocation</th><th>Net cost</th></tr></thead><tbody id="financeExpenses"></tbody></table></div><h3>Bank statement review</h3><p id="bankSummary"></p><div class="table-wrap"><table class="table"><thead><tr><th>Date / account</th><th>Bank narration</th><th>Amount</th><th>Purpose note</th><th>Status</th><th>Action</th></tr></thead><tbody id="bankRows"></tbody></table></div></div>';el('accounting').appendChild(panel)}
  const month=el('financeMonth').value,report=FinanceLedger.report(localSnapshot(),month);
  text('financeTotals',`Revenue ${money(report.revenue)} − client/shared costs ${money(report.directCosts)} − company overheads ${money(report.companyCosts)} − unallocated supplier costs ${money(report.supplierCosts)} = profit ${money(report.profit)}`);
  const other=roundMoney(bankTransactions.filter(t=>(!month||t.transaction_date.slice(0,7)===month)&&t.review?.type==='nonOperating').reduce((sum,t)=>sum+t.amount,0));
  text('financeCash',`Cash flow: collections ${money(report.cash.customerCollections)} + capital ${money(report.cash.capital)} − paid expenses ${money(report.cash.paidExpenses)} − supplier payments ${money(report.cash.supplierPayments)} + other reviewed movements ${money(other)} = ${money(roundMoney(report.cash.net+other))}. Transfers between company accounts do not change total cash.`);
  el('financeClients').innerHTML=report.clients.map(c=>`<tr><td>${escapeHTML(c.name)}</td><td>${money(c.revenue)}</td><td>${money(c.directCosts)}</td><td>${money(c.contribution)}</td></tr>`).join('');
  el('financeExpenses').innerHTML=report.expenses.map(e=>`<tr><td>${escapeHTML(fmt(e.date))}</td><td>${escapeHTML(e.description)}</td><td>${escapeHTML(e.category)}</td><td>${escapeHTML(e.scope==='Client'?clientName(e.client):e.scope==='Shared'?(e.allocations||[]).map(a=>clientName(a.client)+' '+a.percent+'%').join(', '):'Company')}</td><td>${money(e.net)}</td></tr>`).join('')||'<tr><td colspan="5">No expenses in this period.</td></tr>';
  const transactions=bankTransactions.filter(t=>!month||t.transaction_date.slice(0,7)===month).sort((a,b)=>b.transaction_date.localeCompare(a.transaction_date));
  text('bankSummary',`${transactions.length} statement rows · ${transactions.filter(t=>!t.review?.type).length} need review. Importing does not create income or expenses until you review a row.`);
  el('bankRows').innerHTML=transactions.map(t=>`<tr><td>${escapeHTML(fmt(t.transaction_date))}<br>${escapeHTML(t.account_name)}</td><td>${escapeHTML(t.description)}</td><td>${money(t.amount)}</td><td>${escapeHTML(t.note||'Purpose required')}</td><td>${escapeHTML(t.review?.type||'Unreviewed')}</td><td><button class="mini" onclick="FinanceUI.review(${t.id})">${t.review?.type?'View':'Review'}</button></td></tr>`).join('');
 }
 function openBank(){let dialog=el('bankUpload');if(!dialog){dialog=document.createElement('dialog');dialog.id='bankUpload';dialog.style.cssText='width:min(900px,95vw);max-height:90vh;background:var(--surface);color:var(--text);border:1px solid var(--border);padding:20px;border-radius:12px';dialog.innerHTML=`<h2>Monthly bank statement</h2><p>The file stays in your browser. Map date, narration and either a signed amount or debit/credit columns. Positive is money in. Nothing is posted automatically.</p><label>Account <select id="bankAccount">${accountOptions()}</select></label> <label>Statement month <input type="month" id="bankMonth"></label><input type="file" id="bankFile" accept=".xlsx,.xlsm,.csv,.pdf" onchange="FinanceUI.readBank(this.files[0])"><label>Sheet <select id="bankSheet" onchange="FinanceUI.mapBank()"></select></label> <label>Header row <input id="bankHeader" type="number" min="1" value="1" onchange="FinanceUI.mapBank()" style="width:60px"></label><div id="bankMapping"></div><p id="bankError" role="alert" style="color:var(--danger)"></p><button class="btn" onclick="FinanceUI.previewBank()">Preview statement</button> <button class="btn primary" id="bankApply" disabled onclick="FinanceUI.applyBank()">Import for review</button> <button class="btn" onclick="document.getElementById('bankUpload').close()">Close</button><div id="bankPreview"></div>`;document.body.appendChild(dialog)}el('bankAccount').innerHTML=accountOptions();dialog.showModal()}
 async function readBank(file){bankSheets=[];bankPreview=null;el('bankSheet').innerHTML='';el('bankMapping').innerHTML='';el('bankApply').disabled=true;el('bankPreview').innerHTML='';text('bankError','');if(!file)return;if(/\.pdf$/i.test(file.name)){text('bankError','PDF layout needs a bank-specific reader. Use Excel/CSV for this release; provide a redacted PDF sample for the next parser. No PDF records have been imported.');return}try{bankSheets=await ExcelImport.readRows(file);el('bankSheet').innerHTML=bankSheets.map((s,i)=>`<option value="${i}">${escapeHTML(s.name)}</option>`).join('');mapBank()}catch(e){text('bankError',e.message)}}
 function mapBank(){bankPreview=null;el('bankApply').disabled=true;const headers=bankSheets[Number(el('bankSheet').value)]?.rows[Number(el('bankHeader').value)-1];if(!headers)return text('bankError','Select a file and valid header row.');const aliases={date:['date','transactiondate','valuedate'],description:['description','narration','particulars','transactiondetails'],reference:['reference','referenceno','chequeno','chqno'],amount:['amount','signedamount'],debit:['debit','withdrawal','withdrawals','debitamount','withdrawalamt'],credit:['credit','deposit','deposits','creditamount','depositamt'],balance:['balance','closingbalance']};el('bankMapping').innerHTML=Object.keys(aliases).map(field=>`<label>${field} <select id="bankMap-${field}" onchange="document.getElementById('bankApply').disabled=true"><option value="">Not mapped</option>${headers.map((h,i)=>`<option value="${i}" ${aliases[field].includes(String(h).toLowerCase().replace(/[^a-z]/g,''))?'selected':''}>${escapeHTML(h||'Column '+(i+1))}</option>`).join('')}</select></label>`).join(' ')}
 async function previewBank(){
  el('bankApply').disabled=true;text('bankError','');const rows=bankSheets[Number(el('bankSheet').value)]?.rows,start=Number(el('bankHeader').value),account=accounts.find(a=>a.id===Number(el('bankAccount').value)),month=el('bankMonth').value;if(!rows||!account||!month)return text('bankError','Choose file, account and statement month.');const map=Object.fromEntries(['date','description','reference','amount','debit','credit','balance'].map(f=>[f,el('bankMap-'+f).value]));if(map.date===''||map.description===''||(map.amount===''&&map.debit===''&&map.credit===''))return text('bankError','Map date, narration and an amount or debit/credit column.');
  const changes=[],errors=[],occurrences=new Map();let skipped=0;const number=v=>{const text=String(v??'').trim();if(!text||text==='-')return 0;const value=Number(text.replace(/[₹,\s]/g,''));if(!Number.isFinite(value))throw Error('Invalid amount');return roundMoney(value)};
  for(let i=start;i<rows.length;i++){const cells=rows[i],get=f=>map[f]===''?'':cells[Number(map[f])]??'';if(!String(get('date')).trim()&&!String(get('description')).trim())continue;try{const date=ExcelImport.validDate(get('date'));if(date.slice(0,7)!==month)throw Error('Date is outside the selected statement month');const description=String(get('description')).trim(),reference=String(get('reference')).trim();let amount;if(map.amount!=='')amount=number(get('amount'));else{const debit=number(get('debit')),credit=number(get('credit'));if(debit<0||credit<0||debit&&credit)throw Error('Use one positive debit or credit per row');amount=roundMoney(credit-debit)}if(!description||!amount)throw Error('Narration and a non-zero amount are required');const base=JSON.stringify([date,amount,reference,description,String(get('balance'))]);const occurrence=(occurrences.get(base)||0)+1;occurrences.set(base,occurrence);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(base+'|'+occurrence)),fingerprint=Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('');if(bankTransactions.some(t=>t.account_name===account.name&&t.fingerprint===fingerprint)){skipped++;continue}changes.push({account_name:account.name,fingerprint,transaction_date:date,description,reference,amount,note:'',review:{}})}catch(e){errors.push(`Row ${i+1}: ${e.message}`)}}
  bankPreview={changes,errors,account:account.id,month};el('bankPreview').innerHTML=`<p>${changes.length} new · ${skipped} duplicates skipped · ${errors.length} errors</p><ul>${errors.slice(0,20).map(e=>`<li>${escapeHTML(e)}</li>`).join('')}</ul><table class="table"><tbody>${changes.slice(0,40).map(t=>`<tr><td>${escapeHTML(t.transaction_date)}</td><td>${escapeHTML(t.description)}</td><td>${money(t.amount)}</td></tr>`).join('')}</tbody></table>`;el('bankApply').disabled=errors.length>0||!changes.length;
 }
 function applyBank(){if(!bankPreview||bankPreview.errors.length||!cloudReady)return;if(el('bankMonth').value!==bankPreview.month||Number(el('bankAccount').value)!==bankPreview.account)return text('bankError','Selection changed. Preview again.');if(!confirm('Import these rows for review? No financial postings will be created yet.'))return;let next=Math.max(0,...bankTransactions.map(t=>t.id))+1;for(const row of bankPreview.changes)if(!bankTransactions.some(t=>t.account_name===row.account_name&&t.fingerprint===row.fingerprint))bankTransactions.push({...row,id:next++});bankPreview=null;el('bankApply').disabled=true;saveData();renderFinance();el('bankUpload').close()}
 function candidates(t){const found=[];const add=(rows,mode,type,sign,reference)=>{for(const row of rows)if(row.date===t.transaction_date&&roundMoney(sign*row.amount)===t.amount&&accounts.find(a=>a.id===accountIdByName(row[mode]))?.name===t.account_name)found.push({type,reference:reference(row),label:type+' · '+reference(row)})};add(payments,'mode','receipt',1,p=>p.receipt);add(expenses,'account','expense',-1,e=>e.receipt||String(e.cloud_id||e.id));add(ownerCapital,'mode','capital',1,c=>String(c.cloud_id||c.id));add(vendorPayments,'mode','supplier',-1,p=>String(p.cloud_id||p.id));for(const row of bankTransactions){if(row.review?.type==='transfer'&&row.review.other_account===t.account_name&&row.transaction_date===t.transaction_date&&row.amount===-t.amount)found.push({type:'transfer',reference:row.fingerprint,label:'Transfer counterpart · '+row.account_name})}return found}
 function review(id){const t=bankTransactions.find(t=>t.id===id);if(!t)return;reviewing=t;modalType='receipt';el('modalSave').hidden=true;if(t.review?.type){showFinanceModal('Reviewed bank movement',`<p>${escapeHTML(t.description)} · ${money(t.amount)}</p><label for="bankSavedNote">Purpose note</label><input id="bankSavedNote" value="${escapeHTML(t.note)}"><button class="btn" onclick="FinanceUI.updateNote()">Save note</button><p>Classification: ${escapeHTML(t.review.type)} · ${escapeHTML(t.review.reference||t.review.category||'')}</p><p>Review is locked to avoid duplicate postings. Corrections need a controlled reversal.</p>`);return}const matches=candidates(t);t._suggestions=matches;showFinanceModal('Review bank transaction',`<p>${escapeHTML(t.transaction_date)} · ${escapeHTML(t.account_name)} · ${money(t.amount)}<br>${escapeHTML(t.description)}</p><div class="field"><label for="bankPurpose">Why was this payment made / received? *</label><input id="bankPurpose" value="${escapeHTML(t.note)}"></div><div class="field"><label for="bankAction">Treatment</label><select id="bankAction" onchange="FinanceUI.reviewFields()"><option value="">Choose treatment</option>${matches.length?'<option value="match">Match existing ledger record</option>':''}${t.amount>0?'<option value="receipt">New customer collection</option><option value="capital">Owner capital</option>':'<option value="expense">New business expense</option><option value="supplier">New supplier payment</option>'}<option value="transfer">Transfer between company accounts</option><option value="nonOperating">Other non-operating movement</option></select></div><div id="bankTreatment"></div><button class="btn primary" onclick="FinanceUI.approveReview()">Confirm treatment</button>`)}
 function reviewFields(){const t=reviewing,kind=el('bankAction').value;let html='';if(kind==='match')html='<label>Existing record <select id="bankMatch">'+t._suggestions.map((m,i)=>`<option value="${i}">${escapeHTML(m.label)}</option>`).join('')+'</select></label>';if(kind==='receipt')html='<label>Invoice <select id="bankInvoice">'+invoices.filter(i=>roundMoney(i.total-invoicePaid(i.id))>=t.amount).map(i=>`<option value="${i.id}">${escapeHTML(i.no)} · ${escapeHTML(clientName(i.client))}</option>`).join('')+'</select></label>';if(kind==='expense')html=expenseScopeFields()+modalField('Expense category','bankCategory','text','Bank expense')+modalField('GST included','bankGst','number',0,'min="0" step="0.01"');if(kind==='supplier')html='<label>Supplier <select id="bankSupplier">'+vendors.map(v=>`<option value="${v.id}">${escapeHTML(v.name)}</option>`).join('')+'</select></label>';if(kind==='transfer')html='<label>Other company account <select id="bankTransferAccount">'+accounts.filter(a=>a.name!==t.account_name).map(a=>`<option>${escapeHTML(a.name)}</option>`).join('')+'</select></label><p>Records both sides once; the other statement row should be matched to this transfer.</p>';if(kind==='nonOperating')html='<label>Category <select id="bankOther">'+['Owner withdrawal','Loan received','Loan repayment','GST payment','Tax refund'].map(c=>`<option>${c}</option>`).join('')+'</select></label><p>These affect cash, not revenue or operating expense. Internal transfers need matching paired records; do not classify them as income.</p>';el('bankTreatment').innerHTML=html}
 function approveReview(){const t=reviewing;if(!t||t.review?.type)return;const note=el('bankPurpose').value.trim(),kind=el('bankAction').value;if(!note||!kind)return text('financeError','Enter a purpose note and choose treatment.');const reference='BANK-'+t.fingerprint.slice(0,16);let reviewed={type:kind,reference};
  if(kind==='match'){const match=t._suggestions[Number(el('bankMatch').value)];if(!match||!candidates(t).some(m=>m.type===match.type&&m.reference===match.reference))return text('financeError','The matching record changed. Review again.');if(bankTransactions.some(other=>other.id!==t.id&&((other.review?.type==='match'&&other.review?.matchedType===match.type)||other.review?.type===match.type)&&other.review?.reference===match.reference))return text('financeError','Another statement row already matches this ledger record.');reviewed={type:'match',matchedType:match.type,reference:match.reference};
  }else if(kind==='receipt'){const invoice=invoices.find(i=>i.id===Number(el('bankInvoice').value));if(!invoice||t.amount<=0||t.amount>roundMoney(invoice.total-invoicePaid(invoice.id)))return text('financeError','Select an invoice with sufficient outstanding balance.');payments.push({id:Math.max(0,...payments.map(p=>p.id))+1,invoice:invoice.id,receipt:reference,date:t.transaction_date,amount:t.amount,mode:t.account_name});
  }else if(kind==='expense'){const gst=Number(el('bankGst').value),scope=readExpenseScope(),category=el('bankCategory').value.trim();if(t.amount>=0||!validMoney(gst,true)||gst>-t.amount||scope.error||!category)return text('financeError',scope.error||'Enter a valid expense category and GST.');expenses.push({id:Math.max(0,...expenses.map(e=>e.id))+1,...scope.data,date:t.transaction_date,category,vendor:'',description:note,account:t.account_name,amount:-t.amount,gst:roundMoney(gst),receipt:reference});
  }else if(kind==='capital'){if(t.amount<=0)return;const id=Math.max(0,...ownerCapital.map(c=>c.id))+1;reviewed.reference=String(id);reviewed.local_id=id;ownerCapital.push({id,date:t.transaction_date,amount:t.amount,mode:t.account_name});
  }else if(kind==='supplier'){const vendor=Number(el('bankSupplier').value),due=roundMoney(vendorBills.filter(b=>b.vendor===vendor).reduce((sum,b)=>sum+b.amount,0)-vendorPayments.filter(p=>p.vendor===vendor).reduce((sum,p)=>sum+p.amount,0));if(t.amount>=0||-t.amount>due||!vendors.some(v=>v.id===vendor))return text('financeError','Select a supplier with sufficient outstanding balance.');const id=Math.max(0,...vendorPayments.map(p=>p.id))+1;reviewed.reference=String(id);reviewed.local_id=id;vendorPayments.push({id,vendor,date:t.transaction_date,amount:-t.amount,mode:t.account_name});
  }else if(kind==='transfer'){const other=el('bankTransferAccount')?.value;if(!other||other===t.account_name||!accounts.some(a=>a.name===other))return text('financeError','Select the other company account.');reviewed.other_account=other;reviewed.reference=t.fingerprint;
  }else if(kind==='nonOperating'){reviewed.category=el('bankOther').value;const incoming=['Loan received','Tax refund'].includes(reviewed.category);if(incoming!== (t.amount>0))return text('financeError','Category does not match money-in/money-out direction.');
  }else return;
  delete t._suggestions;t.note=note;t.review=reviewed;saveData();renderFinance();renderReports();renderAccountRegister();closeModal();
 }
 function updateNote(){const note=el('bankSavedNote')?.value.trim();if(!reviewing||!note)return text('financeError','Purpose note is required.');reviewing.note=note;saveData();render();closeModal()}
 return {render,openBank,readBank,mapBank,previewBank,applyBank,review,reviewFields,approveReview,updateNote};
})();
